version: '3.3'

volumes:
  postgres_data: {}

services:
  postgres:
    image: 'postgres:14-alpine'
    volumes:
      - './volumes/postgres:/var/lib/postgresql/data'
    env_file: .env

  redis:
    ports:
      - "6379:6379"
    image: 'redis:alpine'

  celery:
    build:
      dockerfile: CeleryDockerfile
      context: ./backend
    command: celery -A config worker -c 4 -l DEBUG
    volumes:
      - './backend:/app'
    depends_on:
      - postgres
      - redis
    env_file: .env

  celery-beat:
    build:
      dockerfile: CeleryDockerfile
      context: ./backend
    command: celery -A config beat -l DEBUG
    volumes:
      - './backend:/app'
    depends_on:
      - postgres
      - redis
    env_file: .env

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - redis
      - postgres
      - celery
      - mailhog
    volumes:
      - .:/app
    command: /start.sh
    entrypoint: /entrypoint.sh
    restart: on-failure
    env_file: .env

  mailhog:
    image: mailhog/mailhog
    ports:
      - '8025:8025'
    logging:
      driver: none
