version: '3.3'

volumes:
  postgres_data: {}

services:
  postgres:
    image: 'postgres:14-alpine'
    volumes:
      - './volumes/postgres:/var/lib/postgresql/data'
    env_file: .env
    
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mailhog
      - postgres
    volumes:
      - .:/app
    command: /gunicorn.sh
    entrypoint: /entrypoint.sh
    restart: on-failure
    env_file: .env
    
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./nginx/stage.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/stage.conf:/etc/nginx/conf.d/default.conf:ro

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
    logging:
      driver: none
