# Generated by Django 3.2.12 on 2024-02-25 04:53

import apps.users.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(blank=True, max_length=128, null=True, verbose_name='Email')),
                ('first_name', models.CharField(blank=True, default='', max_length=32, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, default='', max_length=32, verbose_name='Last name')),
                ('phone_number', models.CharField(max_length=32, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Registered at')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('date_of_birth', models.DateField(blank=True, max_length=8, null=True)),
                ('city', models.CharField(default='jaipur', max_length=108)),
                ('state', models.CharField(default='rajasthan', max_length=108)),
                ('profile_photo', models.ImageField(blank=True, max_length=500, null=True, upload_to=apps.users.models.profile_photo)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
